# Put the world names you want to load or generate below.
# Made with love by Agazed :)
# Official server: mc.skylair.net
worldlist:
#- worldname
#- worldname2
#- worldname3
flatworldlist:
#- flatworldname
#- flatworldname2
#- flatworldname3

# Do you want villages to generate in flat worlds?
generateStructuresInFlatWorlds: false